# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "develop 브랜치 기반의 베타 버전 코드를 빌드한 후 TestFlight에 업로드합니다."
  lane :beta do
    # GitHub Secrets의 API 키 연동
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8_KEY"],
      is_key_content_base64: false
    )

    # GitHub의 EATZ-Client-AppleSilicon-Certificates 리포지토리에서 인증서 다운로드
    match_url = "https://#{ENV['MATCH_GIT_TOKEN']}@github.com/imWhS/EATZ-Client-AppleSilicon-Certificates.git"
    
    match(
      type: "appstore",
      readonly: true,
      git_url: match_url
    )

    # versioning: App Store Connect에서 불러온 최신 빌드 번호에 +1된 값으로 설정
    latest_build_number = app_store_build_number(
      api_key: api_key,
      app_identifier: "com.heextory.eatz"
    )
    increment_build_number(
      build_number: latest_build_number + 1
    )

    # Xcode Archive를 이용한 애플리케이션 빌드
    build_app(
      project: "EATZ-Client-AppleSilicon.xcodeproj",
      scheme: "EATZ-Client-AppleSilicon"
    )

    # TestFlight 업로드
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true # 업로드 후 애플 서버 처리 대기 생략
    )
  end

  desc "main 브랜치 기반의 정식 출시 버전 코드를 빌드한 후 App Store에 배포합니다."
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8_KEY"],
      is_key_content_base64: false
    )

    # GitHub의 EATZ-Client-AppleSilicon-Certificates 리포지토리에서 인증서 다운로드
    match_url = "https://#{ENV['MATCH_GIT_TOKEN']}@github.com/imWhS/EATZ-Client-AppleSilicon-Certificates.git"
    
    match(
      type: "appstore",
      readonly: true,
      git_url: match_url
    )

    # Xcode Archive를 이용한 애플리케이션 빌드
    build_app(
      project: "EATZ-Client-AppleSilicon.xcodeproj",
      scheme: "EATZ-Client-AppleSilicon"
    )

    # App Store Connect로 빌드 업로드
    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true, # App Store 메타 데이터는 App Store Connect를 통해 관리
      skip_screenshots: true,
      submit_for_review: false # 자동 심사 제출 미실행
    )
  end
end
